### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [7]:
import numpy as np

In [43]:
vector = np.random.rand(10)
# vector = np.random.uniform(0, 1, size=10)

M = np.array([[11, 14, 17], [20, 23, 26], [29, 32, 35]])

print("Vector:\n", vector)
print("Vector Shape:", vector.shape)
print("Matrix:\n", M)
print("Matrix Shape:", M.shape)

Vector:
 [0.69182169 0.93278825 0.92404858 0.68898698 0.93416288 0.09030281
 0.57911264 0.94808615 0.71381843 0.38979219]
Vector Shape: (10,)
Matrix:
 [[11 14 17]
 [20 23 26]
 [29 32 35]]
Matrix Shape: (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


Відповідь на завдання 2.1

In [44]:
v1 = np.round(vector + 10, 2)
print("Vector v1 (v + 10, rounded to 2 decimal places):\n", v1)

Vector v1 (v + 10, rounded to 2 decimal places):
 [10.69 10.93 10.92 10.69 10.93 10.09 10.58 10.95 10.71 10.39]


Дана операція відбувається поелементно, тобто кожен елемент вектора збільшується на 10.

Відповідь на завдання 2.2

In [45]:
v2 = vector * 2
print("Vector v2 (v * 2):\n", v2)

Vector v2 (v * 2):
 [1.38364337 1.8655765  1.84809716 1.37797396 1.86832577 0.18060562
 1.15822527 1.8961723  1.42763686 0.77958438]


Дана операція відбувається поелементно, тобто кожен елемент вектора перемножується на 2

Відповідь на завдання 2.3

In [46]:
v3 = vector ** 2
print("Vector v3 (v squared):\n", v3)

Vector v3 (v squared):
 [0.47861725 0.87009392 0.85386578 0.47470306 0.8726603  0.0081546
 0.33537144 0.89886735 0.50953675 0.15193795]


Дана операція відбувається поелементно, тобто кожен елемент вектора підноситься до степеня 2


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [47]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

Відповідь на завдання 3.1

In [48]:
result_matrix = np.dot(B, A)
print("Result of B @ A:\n", result_matrix)

Result of B @ A:
 [[0.7281 0.5202]
 [0.2034 0.2846]]


Щоб вивести результуючу матрицю розмірністю 2х2 з матриць розмірністю 3х2 та 2х3 потрібно транспонувати обидві, або ж перемножити В на А, тоді розмірність також буде 2х2 оскільки форму результуюча матриця набирає з правого множника.

Відповідь на завдання 3.2

In [49]:
result_matrix2 = result_matrix @ C
print("Result of result_matrix * C:\n", result_matrix2)
print("Shape of result_matrix2:", result_matrix2.shape)

Result of result_matrix * C:
 [[0.5202]
 [0.2846]]
Shape of result_matrix2: (2, 1)


Дана матриця отримає зозмірність її зовнішніх елементів розмірності, 2х2 * 2х1 = 2х1

Відповідь на завдання 3.3

In [50]:
result_matrix3 = result_matrix @ D
print("Result of result_matrix * D:\n", result_matrix3)
print("Shape of result_matrix3:", result_matrix3.shape)

Result of result_matrix * D:
 [[0.5202 0.7281]
 [0.2846 0.2034]]
Shape of result_matrix3: (2, 2)


Дана матриця отримає розмірність її зовнішніх елементів розмірності, 2х2 * 2х2 = 2х2


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




Відповідь на завдання 4.1

In [51]:
result_matrix = result_matrix.T
print("Result of B @ A (transposed):\n", result_matrix)


Result of B @ A (transposed):
 [[0.7281 0.2034]
 [0.5202 0.2846]]


Після транспонування рядки початкової матриці стануть стовпцями, а стовпці - рядками

Відповідь на завдання 4.2

In [52]:
vector = vector.T
print("Vector v (transposed):\n", vector)
print("Shape of transposed vector v:", vector.shape)

Vector v (transposed):
 [0.69182169 0.93278825 0.92404858 0.68898698 0.93416288 0.09030281
 0.57911264 0.94808615 0.71381843 0.38979219]
Shape of transposed vector v: (10,)


Транспонування vector не змінює його форму, бо це 1D масив

Відповідь на завдання 4.3

In [53]:
column_vector = np.expand_dims(vector, axis=1)
print("Column vector (v expanded):\n", column_vector)

Column vector (v expanded):
 [[0.69182169]
 [0.93278825]
 [0.92404858]
 [0.68898698]
 [0.93416288]
 [0.09030281]
 [0.57911264]
 [0.94808615]
 [0.71381843]
 [0.38979219]]


Ми міняємо форму вектора з рядка на стовпець

Відповідь на завдання 4.4

In [56]:
column_vector = column_vector.T
print("Column vector (v expanded and transposed):\n", column_vector)
print("Shape of column vector:", column_vector.shape)

Column vector (v expanded and transposed):
 [[0.69182169 0.93278825 0.92404858 0.68898698 0.93416288 0.09030281
  0.57911264 0.94808615 0.71381843 0.38979219]]
Shape of column vector: (1, 10)
